---
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
  tags:
    - rxvt_unicode

- name: install rxvt_unicode packages
  package:
    name: "{{ item }}"
    state: "{{ rxvt_unicode_packages_state }}"
  become: yes
  with_items: "{{ rxvt_unicode_packages }}"
  tags:
    - rxvt_unicode

- name: configure rxvt_unicode
  template:
    src: "{{ rxvt_unicode_conf_template }}"
    dest: "~/{{ rxvt_unicode_conf_path }}"
  when: rxvt_unicode_conf_path is defined
  tags:
    - rxvt_unicode

- name: set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: yes
    insertbefore: BOF
    regexp: "xrdb .*{{ rxvt_unicode_conf_path }}.*"
    line: "xrdb -merge -I$HOME ~/{{ rxvt_unicode_conf_path }}"
  tags:
    - rxvt_unicode
