# vim: ts=2 sw=2 et :
---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
  tags:
    - rxvt_unicode

# Install packages
- name: install rxvt_unicode packages
  package:
    name: "{{ rxvt_unicode_packages }}"
    state: "{{ rxvt_unicode_packages_state }}"
  become: yes
  tags:
    - rxvt_unicode

# Set up configuration file
- name: configure rxvt_unicode
  template:
    src: "{{ rxvt_unicode_conf_template }}"
    dest: "~/{{ rxvt_unicode_conf_path }}"
  when: rxvt_unicode_conf_path is defined
  tags:
    - "rxvt_unicode"
    - "rxvt_unicode_conf"

# Set up xinitrc
- name: set up xinitrc
  lineinfile:
    dest: "~/.xinitrc"
    state: present
    create: yes
    insertbefore: BOF
    regexp: "xrdb .*{{ rxvt_unicode_conf_path }}.*"
    line: "xrdb -merge -I$HOME ~/{{ rxvt_unicode_conf_path }}"
  tags:
    - "rxvt_unicode"
    - "rxvt_unicode_conf"
