---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - always

- name: install urxvt packages
  package:
    name: "{{ item }}"
    state: "{{ rxvt_unicode_packages_state }}"
  become: yes
  with_items: "{{ rxvt_unicode_packages }}"
  tags:
    - install

- name: configure urxvt
  template:
    src: "{{ rxvt_unicode_conf_template }}"
    dest: "~/{{ rxvt_unicode_conf_path }}"
  tags:
    - configure

- name: configure xresources
  lineinfile:
    dest: "~/{{ rxvt_unicode_xresources_path }}"
    state: present
    create: yes
    insertbefore: "^#include"
    line: '#include "{{ rxvt_unicode_conf_path }}"'

- name: set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: yes
    insertbefore: BOF
    regexp: "xrdb .*{{ rxvt_unicode_xresources_path }}.*"
    line: "xrdb -merge -I$HOME ~/{{ rxvt_unicode_xresources_path }}"
  tags:
    - configure
